version: '3'
services:
  nats:
    image: nats:1.4.1
  nchats-1:
    build: .
    depends_on: [ nats ]
    ports: [ "8080:8080" ]
    environment:
      NATSURL: nats
  nchats-2:
    build: .
    depends_on: [ nats ]
    ports: [ "8081:8080" ]
    environment:
      NATSURL: nats
